/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BookId = IDL.Nat;
export const BookStatus = IDL.Variant({
  'sold' : IDL.Null,
  'available' : IDL.Null,
});
export const Timestamp = IDL.Nat;
export const UserId = IDL.Principal;
export const Book = IDL.Record({
  'id' : BookId,
  'status' : BookStatus,
  'title' : IDL.Text,
  'subject' : IDL.Text,
  'createdAt' : Timestamp,
  'photoUrl' : IDL.Opt(IDL.Text),
  'author' : IDL.Text,
  'sellerId' : UserId,
  'price' : IDL.Nat,
});
export const InterestId = IDL.Nat;
export const Interest = IDL.Record({
  'id' : InterestId,
  'createdAt' : Timestamp,
  'bookId' : BookId,
  'buyerId' : UserId,
});
export const NotificationId = IDL.Nat;
export const Notification = IDL.Record({
  'id' : NotificationId,
  'bookTitle' : IDL.Text,
  'buyerEmail' : IDL.Text,
  'createdAt' : Timestamp,
  'buyerPhone' : IDL.Text,
  'bookId' : BookId,
  'isRead' : IDL.Bool,
  'buyerId' : UserId,
  'buyerName' : IDL.Text,
  'interestId' : InterestId,
});
export const User = IDL.Record({
  'id' : UserId,
  'collegeName' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'email' : IDL.Text,
  'isAdmin' : IDL.Bool,
  'phone' : IDL.Text,
});
export const InterestWithDetails = IDL.Record({
  'id' : InterestId,
  'bookTitle' : IDL.Text,
  'buyerEmail' : IDL.Text,
  'createdAt' : Timestamp,
  'buyerPhone' : IDL.Text,
  'bookId' : BookId,
  'buyerId' : UserId,
  'buyerName' : IDL.Text,
});
export const BookInput = IDL.Record({
  'title' : IDL.Text,
  'subject' : IDL.Text,
  'photoUrl' : IDL.Opt(IDL.Text),
  'author' : IDL.Text,
  'price' : IDL.Nat,
});
export const UserInput = IDL.Record({
  'collegeName' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '__books' : IDL.Func(
      [IDL.Opt(BookId), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(BookId, Book))],
      ['query'],
    ),
  '__interests' : IDL.Func(
      [IDL.Opt(InterestId), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(InterestId, Interest))],
      ['query'],
    ),
  '__nextBookId' : IDL.Func([], [IDL.Reserved], ['query']),
  '__nextInterestId' : IDL.Func([], [IDL.Reserved], ['query']),
  '__nextNotificationId' : IDL.Func([], [IDL.Reserved], ['query']),
  '__notifications' : IDL.Func(
      [IDL.Opt(NotificationId), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(NotificationId, Notification))],
      ['query'],
    ),
  '__users' : IDL.Func(
      [IDL.Opt(UserId), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(UserId, User))],
      ['query'],
    ),
  'adminConfirmAvailability' : IDL.Func([BookId], [IDL.Opt(Book)], []),
  'adminDeleteBook' : IDL.Func([BookId], [IDL.Bool], []),
  'adminDeleteUser' : IDL.Func([UserId], [IDL.Bool], []),
  'adminGetNewInterestNotifications' : IDL.Func(
      [],
      [IDL.Vec(InterestWithDetails)],
      [],
    ),
  'adminGetSellerContact' : IDL.Func(
      [BookId],
      [
        IDL.Opt(
          IDL.Record({
            'name' : IDL.Text,
            'email' : IDL.Text,
            'phone' : IDL.Text,
          })
        ),
      ],
      [],
    ),
  'adminListAllInterests' : IDL.Func([], [IDL.Vec(InterestWithDetails)], []),
  'adminMarkBookSold' : IDL.Func([BookId], [IDL.Opt(Book)], []),
  'adminUpdateBook' : IDL.Func([BookId, BookInput], [IDL.Opt(Book)], []),
  'createBook' : IDL.Func([BookInput], [Book], []),
  'deleteBook' : IDL.Func([BookId], [IDL.Bool], []),
  'deleteInterest' : IDL.Func([InterestId], [IDL.Bool], []),
  'deleteUser' : IDL.Func([UserId], [IDL.Bool], []),
  'expressInterest' : IDL.Func([BookId], [Interest], []),
  'getAdminNotifications' : IDL.Func([], [IDL.Vec(Notification)], []),
  'getBook' : IDL.Func([BookId], [IDL.Opt(Book)], ['query']),
  'getInterest' : IDL.Func([InterestId], [IDL.Opt(Interest)], ['query']),
  'getInterestsForMyBooks' : IDL.Func([], [IDL.Vec(Interest)], []),
  'getMyBooks' : IDL.Func([], [IDL.Vec(Book)], []),
  'getMyInterests' : IDL.Func([], [IDL.Vec(Interest)], []),
  'getMyProfile' : IDL.Func([], [IDL.Opt(User)], ['query']),
  'getUnreadAdminNotificationCount' : IDL.Func([], [IDL.Nat], []),
  'getUser' : IDL.Func([UserId], [IDL.Opt(User)], ['query']),
  'listBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
  'listInterests' : IDL.Func([], [IDL.Vec(Interest)], ['query']),
  'listInterestsWithDetails' : IDL.Func(
      [],
      [IDL.Vec(InterestWithDetails)],
      ['query'],
    ),
  'listUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'markAdminNotificationAsRead' : IDL.Func(
      [NotificationId],
      [IDL.Opt(Notification)],
      [],
    ),
  'registerUser' : IDL.Func([UserInput], [User], []),
  'searchBooks' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Vec(Book)],
      ['query'],
    ),
  'setAdmin' : IDL.Func([UserId, IDL.Bool], [IDL.Opt(User)], []),
  'updateBook' : IDL.Func([BookId, BookInput], [IDL.Opt(Book)], []),
  'updateMyProfile' : IDL.Func([UserInput], [IDL.Opt(User)], []),
  'updateUser' : IDL.Func([UserId, UserInput], [IDL.Opt(User)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BookId = IDL.Nat;
  const BookStatus = IDL.Variant({ 'sold' : IDL.Null, 'available' : IDL.Null });
  const Timestamp = IDL.Nat;
  const UserId = IDL.Principal;
  const Book = IDL.Record({
    'id' : BookId,
    'status' : BookStatus,
    'title' : IDL.Text,
    'subject' : IDL.Text,
    'createdAt' : Timestamp,
    'photoUrl' : IDL.Opt(IDL.Text),
    'author' : IDL.Text,
    'sellerId' : UserId,
    'price' : IDL.Nat,
  });
  const InterestId = IDL.Nat;
  const Interest = IDL.Record({
    'id' : InterestId,
    'createdAt' : Timestamp,
    'bookId' : BookId,
    'buyerId' : UserId,
  });
  const NotificationId = IDL.Nat;
  const Notification = IDL.Record({
    'id' : NotificationId,
    'bookTitle' : IDL.Text,
    'buyerEmail' : IDL.Text,
    'createdAt' : Timestamp,
    'buyerPhone' : IDL.Text,
    'bookId' : BookId,
    'isRead' : IDL.Bool,
    'buyerId' : UserId,
    'buyerName' : IDL.Text,
    'interestId' : InterestId,
  });
  const User = IDL.Record({
    'id' : UserId,
    'collegeName' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'email' : IDL.Text,
    'isAdmin' : IDL.Bool,
    'phone' : IDL.Text,
  });
  const InterestWithDetails = IDL.Record({
    'id' : InterestId,
    'bookTitle' : IDL.Text,
    'buyerEmail' : IDL.Text,
    'createdAt' : Timestamp,
    'buyerPhone' : IDL.Text,
    'bookId' : BookId,
    'buyerId' : UserId,
    'buyerName' : IDL.Text,
  });
  const BookInput = IDL.Record({
    'title' : IDL.Text,
    'subject' : IDL.Text,
    'photoUrl' : IDL.Opt(IDL.Text),
    'author' : IDL.Text,
    'price' : IDL.Nat,
  });
  const UserInput = IDL.Record({
    'collegeName' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '__books' : IDL.Func(
        [IDL.Opt(BookId), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(BookId, Book))],
        ['query'],
      ),
    '__interests' : IDL.Func(
        [IDL.Opt(InterestId), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(InterestId, Interest))],
        ['query'],
      ),
    '__nextBookId' : IDL.Func([], [IDL.Reserved], ['query']),
    '__nextInterestId' : IDL.Func([], [IDL.Reserved], ['query']),
    '__nextNotificationId' : IDL.Func([], [IDL.Reserved], ['query']),
    '__notifications' : IDL.Func(
        [IDL.Opt(NotificationId), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(NotificationId, Notification))],
        ['query'],
      ),
    '__users' : IDL.Func(
        [IDL.Opt(UserId), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(UserId, User))],
        ['query'],
      ),
    'adminConfirmAvailability' : IDL.Func([BookId], [IDL.Opt(Book)], []),
    'adminDeleteBook' : IDL.Func([BookId], [IDL.Bool], []),
    'adminDeleteUser' : IDL.Func([UserId], [IDL.Bool], []),
    'adminGetNewInterestNotifications' : IDL.Func(
        [],
        [IDL.Vec(InterestWithDetails)],
        [],
      ),
    'adminGetSellerContact' : IDL.Func(
        [BookId],
        [
          IDL.Opt(
            IDL.Record({
              'name' : IDL.Text,
              'email' : IDL.Text,
              'phone' : IDL.Text,
            })
          ),
        ],
        [],
      ),
    'adminListAllInterests' : IDL.Func([], [IDL.Vec(InterestWithDetails)], []),
    'adminMarkBookSold' : IDL.Func([BookId], [IDL.Opt(Book)], []),
    'adminUpdateBook' : IDL.Func([BookId, BookInput], [IDL.Opt(Book)], []),
    'createBook' : IDL.Func([BookInput], [Book], []),
    'deleteBook' : IDL.Func([BookId], [IDL.Bool], []),
    'deleteInterest' : IDL.Func([InterestId], [IDL.Bool], []),
    'deleteUser' : IDL.Func([UserId], [IDL.Bool], []),
    'expressInterest' : IDL.Func([BookId], [Interest], []),
    'getAdminNotifications' : IDL.Func([], [IDL.Vec(Notification)], []),
    'getBook' : IDL.Func([BookId], [IDL.Opt(Book)], ['query']),
    'getInterest' : IDL.Func([InterestId], [IDL.Opt(Interest)], ['query']),
    'getInterestsForMyBooks' : IDL.Func([], [IDL.Vec(Interest)], []),
    'getMyBooks' : IDL.Func([], [IDL.Vec(Book)], []),
    'getMyInterests' : IDL.Func([], [IDL.Vec(Interest)], []),
    'getMyProfile' : IDL.Func([], [IDL.Opt(User)], ['query']),
    'getUnreadAdminNotificationCount' : IDL.Func([], [IDL.Nat], []),
    'getUser' : IDL.Func([UserId], [IDL.Opt(User)], ['query']),
    'listBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
    'listInterests' : IDL.Func([], [IDL.Vec(Interest)], ['query']),
    'listInterestsWithDetails' : IDL.Func(
        [],
        [IDL.Vec(InterestWithDetails)],
        ['query'],
      ),
    'listUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'markAdminNotificationAsRead' : IDL.Func(
        [NotificationId],
        [IDL.Opt(Notification)],
        [],
      ),
    'registerUser' : IDL.Func([UserInput], [User], []),
    'searchBooks' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Vec(Book)],
        ['query'],
      ),
    'setAdmin' : IDL.Func([UserId, IDL.Bool], [IDL.Opt(User)], []),
    'updateBook' : IDL.Func([BookId, BookInput], [IDL.Opt(Book)], []),
    'updateMyProfile' : IDL.Func([UserInput], [IDL.Opt(User)], []),
    'updateUser' : IDL.Func([UserId, UserInput], [IDL.Opt(User)], []),
  });
};

export const init = ({ IDL }) => { return []; };