/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Book {
  'id' : BookId,
  'status' : BookStatus,
  'title' : string,
  'subject' : string,
  'createdAt' : Timestamp,
  'photoUrl' : [] | [string],
  'author' : string,
  'sellerId' : UserId,
  'price' : bigint,
}
export type BookId = bigint;
export interface BookInput {
  'title' : string,
  'subject' : string,
  'photoUrl' : [] | [string],
  'author' : string,
  'price' : bigint,
}
export type BookStatus = { 'sold' : null } |
  { 'available' : null };
export interface Interest {
  'id' : InterestId,
  'createdAt' : Timestamp,
  'bookId' : BookId,
  'buyerId' : UserId,
}
export type InterestId = bigint;
export interface InterestWithDetails {
  'id' : InterestId,
  'bookTitle' : string,
  'buyerEmail' : string,
  'createdAt' : Timestamp,
  'buyerPhone' : string,
  'bookId' : BookId,
  'buyerId' : UserId,
  'buyerName' : string,
}
export interface Notification {
  'id' : NotificationId,
  'bookTitle' : string,
  'buyerEmail' : string,
  'createdAt' : Timestamp,
  'buyerPhone' : string,
  'bookId' : BookId,
  'isRead' : boolean,
  'buyerId' : UserId,
  'buyerName' : string,
  'interestId' : InterestId,
}
export type NotificationId = bigint;
export type Timestamp = bigint;
export interface User {
  'id' : UserId,
  'collegeName' : [] | [string],
  'name' : string,
  'createdAt' : Timestamp,
  'email' : string,
  'isAdmin' : boolean,
  'phone' : string,
}
export type UserId = Principal;
export interface UserInput {
  'collegeName' : [] | [string],
  'name' : string,
  'email' : string,
  'phone' : string,
}
export interface _SERVICE {
  '__books' : ActorMethod<
    [[] | [BookId], [] | [bigint]],
    Array<[BookId, Book]>
  >,
  '__interests' : ActorMethod<
    [[] | [InterestId], [] | [bigint]],
    Array<[InterestId, Interest]>
  >,
  '__nextBookId' : ActorMethod<[], any>,
  '__nextInterestId' : ActorMethod<[], any>,
  '__nextNotificationId' : ActorMethod<[], any>,
  '__notifications' : ActorMethod<
    [[] | [NotificationId], [] | [bigint]],
    Array<[NotificationId, Notification]>
  >,
  '__users' : ActorMethod<
    [[] | [UserId], [] | [bigint]],
    Array<[UserId, User]>
  >,
  'adminConfirmAvailability' : ActorMethod<[BookId], [] | [Book]>,
  'adminDeleteBook' : ActorMethod<[BookId], boolean>,
  'adminDeleteUser' : ActorMethod<[UserId], boolean>,
  'adminGetNewInterestNotifications' : ActorMethod<
    [],
    Array<InterestWithDetails>
  >,
  'adminGetSellerContact' : ActorMethod<
    [BookId],
    [] | [{ 'name' : string, 'email' : string, 'phone' : string }]
  >,
  'adminListAllInterests' : ActorMethod<[], Array<InterestWithDetails>>,
  'adminMarkBookSold' : ActorMethod<[BookId], [] | [Book]>,
  'adminUpdateBook' : ActorMethod<[BookId, BookInput], [] | [Book]>,
  'createBook' : ActorMethod<[BookInput], Book>,
  'deleteBook' : ActorMethod<[BookId], boolean>,
  'deleteInterest' : ActorMethod<[InterestId], boolean>,
  'deleteUser' : ActorMethod<[UserId], boolean>,
  'expressInterest' : ActorMethod<[BookId], Interest>,
  'getAdminNotifications' : ActorMethod<[], Array<Notification>>,
  'getBook' : ActorMethod<[BookId], [] | [Book]>,
  'getInterest' : ActorMethod<[InterestId], [] | [Interest]>,
  'getInterestsForMyBooks' : ActorMethod<[], Array<Interest>>,
  'getMyBooks' : ActorMethod<[], Array<Book>>,
  'getMyInterests' : ActorMethod<[], Array<Interest>>,
  'getMyProfile' : ActorMethod<[], [] | [User]>,
  'getUnreadAdminNotificationCount' : ActorMethod<[], bigint>,
  'getUser' : ActorMethod<[UserId], [] | [User]>,
  'listBooks' : ActorMethod<[], Array<Book>>,
  'listInterests' : ActorMethod<[], Array<Interest>>,
  'listInterestsWithDetails' : ActorMethod<[], Array<InterestWithDetails>>,
  'listUsers' : ActorMethod<[], Array<User>>,
  'markAdminNotificationAsRead' : ActorMethod<
    [NotificationId],
    [] | [Notification]
  >,
  'registerUser' : ActorMethod<[UserInput], User>,
  'searchBooks' : ActorMethod<[[] | [string], [] | [string]], Array<Book>>,
  'setAdmin' : ActorMethod<[UserId, boolean], [] | [User]>,
  'updateBook' : ActorMethod<[BookId, BookInput], [] | [Book]>,
  'updateMyProfile' : ActorMethod<[UserInput], [] | [User]>,
  'updateUser' : ActorMethod<[UserId, UserInput], [] | [User]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];