/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export type UserId = Principal;
export type Timestamp = bigint;
export interface InterestWithDetails {
    id: InterestId;
    bookTitle: string;
    buyerEmail: string;
    createdAt: Timestamp;
    buyerPhone: string;
    bookId: BookId;
    buyerId: UserId;
    buyerName: string;
}
export interface BookInput {
    title: string;
    subject: string;
    photoUrl?: string;
    author: string;
    price: bigint;
}
export interface Notification {
    id: NotificationId;
    bookTitle: string;
    buyerEmail: string;
    createdAt: Timestamp;
    buyerPhone: string;
    bookId: BookId;
    isRead: boolean;
    buyerId: UserId;
    buyerName: string;
    interestId: InterestId;
}
export interface User {
    id: UserId;
    collegeName?: string;
    name: string;
    createdAt: Timestamp;
    email: string;
    isAdmin: boolean;
    phone: string;
}
export type NotificationId = bigint;
export type InterestId = bigint;
export interface Interest {
    id: InterestId;
    createdAt: Timestamp;
    bookId: BookId;
    buyerId: UserId;
}
export interface UserInput {
    collegeName?: string;
    name: string;
    email: string;
    phone: string;
}
export type BookId = bigint;
export interface Book {
    id: BookId;
    status: BookStatus;
    title: string;
    subject: string;
    createdAt: Timestamp;
    photoUrl?: string;
    author: string;
    sellerId: UserId;
    price: bigint;
}
export enum BookStatus {
    sold = "sold",
    available = "available"
}
export interface backendInterface {
    __books(ko: BookId | null, count: bigint | null): Promise<Array<[BookId, Book]>>;
    __interests(ko: InterestId | null, count: bigint | null): Promise<Array<[InterestId, Interest]>>;
    __nextBookId(): Promise<any>;
    __nextInterestId(): Promise<any>;
    __nextNotificationId(): Promise<any>;
    __notifications(ko: NotificationId | null, count: bigint | null): Promise<Array<[NotificationId, Notification]>>;
    __users(ko: UserId | null, count: bigint | null): Promise<Array<[UserId, User]>>;
    adminConfirmAvailability(id: BookId): Promise<Book | null>;
    adminDeleteBook(id: BookId): Promise<boolean>;
    adminDeleteUser(id: UserId): Promise<boolean>;
    adminGetNewInterestNotifications(): Promise<Array<InterestWithDetails>>;
    adminGetSellerContact(bookId: BookId): Promise<{
        name: string;
        email: string;
        phone: string;
    } | null>;
    adminListAllInterests(): Promise<Array<InterestWithDetails>>;
    adminMarkBookSold(id: BookId): Promise<Book | null>;
    adminUpdateBook(id: BookId, input: BookInput): Promise<Book | null>;
    createBook(input: BookInput): Promise<Book>;
    deleteBook(id: BookId): Promise<boolean>;
    deleteInterest(id: InterestId): Promise<boolean>;
    deleteUser(id: UserId): Promise<boolean>;
    expressInterest(bookId: BookId): Promise<Interest>;
    getAdminNotifications(): Promise<Array<Notification>>;
    getBook(id: BookId): Promise<Book | null>;
    getInterest(id: InterestId): Promise<Interest | null>;
    getInterestsForMyBooks(): Promise<Array<Interest>>;
    getMyBooks(): Promise<Array<Book>>;
    getMyInterests(): Promise<Array<Interest>>;
    getMyProfile(): Promise<User | null>;
    getUnreadAdminNotificationCount(): Promise<bigint>;
    getUser(id: UserId): Promise<User | null>;
    listBooks(): Promise<Array<Book>>;
    listInterests(): Promise<Array<Interest>>;
    listInterestsWithDetails(): Promise<Array<InterestWithDetails>>;
    listUsers(): Promise<Array<User>>;
    markAdminNotificationAsRead(id: NotificationId): Promise<Notification | null>;
    registerUser(input: UserInput): Promise<User>;
    searchBooks(searchTerm: string | null, collegeFilter: string | null): Promise<Array<Book>>;
    setAdmin(id: UserId, admin: boolean): Promise<User | null>;
    updateBook(id: BookId, input: BookInput): Promise<Book | null>;
    updateMyProfile(input: UserInput): Promise<User | null>;
    updateUser(id: UserId, input: UserInput): Promise<User | null>;
}
import type { Book as _Book, BookId as _BookId, BookInput as _BookInput, BookStatus as _BookStatus, Interest as _Interest, InterestId as _InterestId, Notification as _Notification, NotificationId as _NotificationId, Timestamp as _Timestamp, User as _User, UserId as _UserId, UserInput as _UserInput } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async __books(arg0: BookId | null, arg1: bigint | null): Promise<Array<[BookId, Book]>> {
        if (this.processError) {
            try {
                const result = await this.actor.__books(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__books(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async __interests(arg0: InterestId | null, arg1: bigint | null): Promise<Array<[InterestId, Interest]>> {
        if (this.processError) {
            try {
                const result = await this.actor.__interests(to_candid_opt_n10(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__interests(to_candid_opt_n10(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async __nextBookId(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__nextBookId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__nextBookId();
            return result;
        }
    }
    async __nextInterestId(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__nextInterestId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__nextInterestId();
            return result;
        }
    }
    async __nextNotificationId(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__nextNotificationId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__nextNotificationId();
            return result;
        }
    }
    async __notifications(arg0: NotificationId | null, arg1: bigint | null): Promise<Array<[NotificationId, Notification]>> {
        if (this.processError) {
            try {
                const result = await this.actor.__notifications(to_candid_opt_n11(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__notifications(to_candid_opt_n11(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async __users(arg0: UserId | null, arg1: bigint | null): Promise<Array<[UserId, User]>> {
        if (this.processError) {
            try {
                const result = await this.actor.__users(to_candid_opt_n12(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__users(to_candid_opt_n12(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminConfirmAvailability(arg0: BookId): Promise<Book | null> {
        if (this.processError) {
            try {
                const result = await this.actor.adminConfirmAvailability(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminConfirmAvailability(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminDeleteBook(arg0: BookId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteBook(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteBook(arg0);
            return result;
        }
    }
    async adminDeleteUser(arg0: UserId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteUser(arg0);
            return result;
        }
    }
    async adminGetNewInterestNotifications(): Promise<Array<InterestWithDetails>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetNewInterestNotifications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetNewInterestNotifications();
            return result;
        }
    }
    async adminGetSellerContact(arg0: BookId): Promise<{
        name: string;
        email: string;
        phone: string;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetSellerContact(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetSellerContact(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminListAllInterests(): Promise<Array<InterestWithDetails>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListAllInterests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListAllInterests();
            return result;
        }
    }
    async adminMarkBookSold(arg0: BookId): Promise<Book | null> {
        if (this.processError) {
            try {
                const result = await this.actor.adminMarkBookSold(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminMarkBookSold(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminUpdateBook(arg0: BookId, arg1: BookInput): Promise<Book | null> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateBook(arg0, to_candid_BookInput_n19(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateBook(arg0, to_candid_BookInput_n19(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async createBook(arg0: BookInput): Promise<Book> {
        if (this.processError) {
            try {
                const result = await this.actor.createBook(to_candid_BookInput_n19(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Book_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBook(to_candid_BookInput_n19(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Book_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteBook(arg0: BookId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBook(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBook(arg0);
            return result;
        }
    }
    async deleteInterest(arg0: InterestId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInterest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInterest(arg0);
            return result;
        }
    }
    async deleteUser(arg0: UserId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUser(arg0);
            return result;
        }
    }
    async expressInterest(arg0: BookId): Promise<Interest> {
        if (this.processError) {
            try {
                const result = await this.actor.expressInterest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.expressInterest(arg0);
            return result;
        }
    }
    async getAdminNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminNotifications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminNotifications();
            return result;
        }
    }
    async getBook(arg0: BookId): Promise<Book | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBook(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBook(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInterest(arg0: InterestId): Promise<Interest | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInterest(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInterest(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInterestsForMyBooks(): Promise<Array<Interest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInterestsForMyBooks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInterestsForMyBooks();
            return result;
        }
    }
    async getMyBooks(): Promise<Array<Book>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyBooks();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyBooks();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyInterests(): Promise<Array<Interest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyInterests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyInterests();
            return result;
        }
    }
    async getMyProfile(): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUnreadAdminNotificationCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadAdminNotificationCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadAdminNotificationCount();
            return result;
        }
    }
    async getUser(arg0: UserId): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUser(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUser(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async listBooks(): Promise<Array<Book>> {
        if (this.processError) {
            try {
                const result = await this.actor.listBooks();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listBooks();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async listInterests(): Promise<Array<Interest>> {
        if (this.processError) {
            try {
                const result = await this.actor.listInterests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listInterests();
            return result;
        }
    }
    async listInterestsWithDetails(): Promise<Array<InterestWithDetails>> {
        if (this.processError) {
            try {
                const result = await this.actor.listInterestsWithDetails();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listInterestsWithDetails();
            return result;
        }
    }
    async listUsers(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUsers();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUsers();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async markAdminNotificationAsRead(arg0: NotificationId): Promise<Notification | null> {
        if (this.processError) {
            try {
                const result = await this.actor.markAdminNotificationAsRead(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAdminNotificationAsRead(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerUser(arg0: UserInput): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(to_candid_UserInput_n26(this._uploadFile, this._downloadFile, arg0));
                return from_candid_User_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(to_candid_UserInput_n26(this._uploadFile, this._downloadFile, arg0));
            return from_candid_User_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchBooks(arg0: string | null, arg1: string | null): Promise<Array<Book>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchBooks(to_candid_opt_n28(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchBooks(to_candid_opt_n28(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async setAdmin(arg0: UserId, arg1: boolean): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.setAdmin(arg0, arg1);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAdmin(arg0, arg1);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateBook(arg0: BookId, arg1: BookInput): Promise<Book | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBook(arg0, to_candid_BookInput_n19(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBook(arg0, to_candid_BookInput_n19(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateMyProfile(arg0: UserInput): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMyProfile(to_candid_UserInput_n26(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMyProfile(to_candid_UserInput_n26(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateUser(arg0: UserId, arg1: UserInput): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUser(arg0, to_candid_UserInput_n26(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUser(arg0, to_candid_UserInput_n26(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_BookStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookStatus): BookStatus {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Book_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Book): Book {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_User_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Book]): Book | null {
    return value.length === 0 ? null : from_candid_Book_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        name: string;
        email: string;
        phone: string;
    }]): {
    name: string;
    email: string;
    phone: string;
} | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Interest]): Interest | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_User]): User | null {
    return value.length === 0 ? null : from_candid_User_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Notification]): Notification | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    collegeName: [] | [string];
    name: string;
    createdAt: _Timestamp;
    email: string;
    isAdmin: boolean;
    phone: string;
}): {
    id: UserId;
    collegeName?: string;
    name: string;
    createdAt: Timestamp;
    email: string;
    isAdmin: boolean;
    phone: string;
} {
    return {
        id: value.id,
        collegeName: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.collegeName)),
        name: value.name,
        createdAt: value.createdAt,
        email: value.email,
        isAdmin: value.isAdmin,
        phone: value.phone
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _BookId;
    status: _BookStatus;
    title: string;
    subject: string;
    createdAt: _Timestamp;
    photoUrl: [] | [string];
    author: string;
    sellerId: _UserId;
    price: bigint;
}): {
    id: BookId;
    status: BookStatus;
    title: string;
    subject: string;
    createdAt: Timestamp;
    photoUrl?: string;
    author: string;
    sellerId: UserId;
    price: bigint;
} {
    return {
        id: value.id,
        status: from_candid_BookStatus_n7(_uploadFile, _downloadFile, value.status),
        title: value.title,
        subject: value.subject,
        createdAt: value.createdAt,
        photoUrl: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.photoUrl)),
        author: value.author,
        sellerId: value.sellerId,
        price: value.price
    };
}
function from_candid_tuple_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_UserId, _User]): [UserId, User] {
    return [
        value[0],
        from_candid_User_n15(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_BookId, _Book]): [BookId, Book] {
    return [
        value[0],
        from_candid_Book_n5(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sold: null;
} | {
    available: null;
}): BookStatus {
    return "sold" in value ? BookStatus.sold : "available" in value ? BookStatus.available : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_UserId, _User]>): Array<[UserId, User]> {
    return value.map((x)=>from_candid_tuple_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Book>): Array<Book> {
    return value.map((x)=>from_candid_Book_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_User>): Array<User> {
    return value.map((x)=>from_candid_User_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_BookId, _Book]>): Array<[BookId, Book]> {
    return value.map((x)=>from_candid_tuple_n4(_uploadFile, _downloadFile, x));
}
function to_candid_BookInput_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookInput): _BookInput {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_UserInput_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserInput): _UserInput {
    return to_candid_record_n27(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookId | null): [] | [_BookId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InterestId | null): [] | [_InterestId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NotificationId | null): [] | [_NotificationId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserId | null): [] | [_UserId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    subject: string;
    photoUrl?: string;
    author: string;
    price: bigint;
}): {
    title: string;
    subject: string;
    photoUrl: [] | [string];
    author: string;
    price: bigint;
} {
    return {
        title: value.title,
        subject: value.subject,
        photoUrl: value.photoUrl ? candid_some(value.photoUrl) : candid_none(),
        author: value.author,
        price: value.price
    };
}
function to_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    collegeName?: string;
    name: string;
    email: string;
    phone: string;
}): {
    collegeName: [] | [string];
    name: string;
    email: string;
    phone: string;
} {
    return {
        collegeName: value.collegeName ? candid_some(value.collegeName) : candid_none(),
        name: value.name,
        email: value.email,
        phone: value.phone
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
